#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop hybrid-web.service    || true
            systemctl stop hybrid-worker.service || true
        fi
        ;;
    failed-upgrade)
        ;;
esac

#DEBHELPER#
exit 0
